export type TemplateItem = {
    id: string;
    name: string;
    src: string;
    category: 'shirt' | 'dress' | 'hoodie' | 'skirt' | 'jackets' | 'shorts' | 'tank-tops' | 'pants';
    garmentLabel: string;
    generationCategoryId: string;
};

export const TEMPLATES: TemplateItem[] = [
    {
        id: 'basic-tshirt-1',
        name: 'Basic Round neck T-Shirt',
        src: '/templates/shirt1.png',
        category: 'shirt',
        garmentLabel: 'Round Neck T-Shirt',
        generationCategoryId: 't-shirt',
    },
    {
        id: 'basic-tshirt-2',
        name: 'Basic V-neck T-Shirt',
        src: '/templates/shirt2.png',
        category: 'shirt',
        garmentLabel: 'V-Neck T-Shirt',
        generationCategoryId: 't-shirt',
    },
    {
        id: 'basic-tshirt-3',
        name: 'Basic collared T-Shirt',
        src: '/templates/shirt3.png',
        category: 'shirt',
        garmentLabel: 'Collared T-Shirt',
        generationCategoryId: 't-shirt',
    },
    {
        id: 'hoodie-1',
        name: 'Hoodie Template 1',
        src: '/templates/hoodie1.png',
        category: 'hoodie',
        garmentLabel: 'Hoodie',
        generationCategoryId: 'hoodie',
    },
    {
        id: 'hoodie-2',
        name: 'Hoodie Template 2',
        src: '/templates/hoodie2.png',
        category: 'hoodie',
        garmentLabel: 'Hoodie',
        generationCategoryId: 'hoodie',
    },
    {
        id: 'hoodie-3',
        name: 'Hoodie Template 3',
        src: '/templates/hoodie3.png',
        category: 'hoodie',
        garmentLabel: 'Hoodie',
        generationCategoryId: 'hoodie',
    },
    {
        id: 'dress-1',
        name: 'A-line Dress',
        src: '/templates/dress1.png',
        category: 'dress',
        garmentLabel: 'A-Line Dress',
        generationCategoryId: 'dress',
    },
    {
        id: 'dress-2',
        name: 'Basic Dress',
        src: '/templates/dress2.png',
        category: 'dress',
        garmentLabel: 'Dress',
        generationCategoryId: 'dress',
    },
    {
        id: 'dress-3',
        name: 'Flared Dress',
        src: '/templates/dress3.png',
        category: 'dress',
        garmentLabel: 'Flared Dress',
        generationCategoryId: 'dress',
    },
    {
        id: 'jacket-1',
        name: 'Puffer Jacket',
        src: '/templates/jacket1.png',
        category: 'jackets',
        garmentLabel: 'Puffer Jacket',
        generationCategoryId: 'jacket',
    },
    {
        id: 'jacket-2',
        name: 'Hoodie Jacket',
        src: '/templates/jacket2.png',
        category: 'jackets',
        garmentLabel: 'Hoodie Jacket',
        generationCategoryId: 'jacket',
    },
    {
        id: 'jacket-3',
        name: 'Denim Jacket',
        src: '/templates/jacket3.png',
        category: 'jackets',
        garmentLabel: 'Denim Jacket',
        generationCategoryId: 'jacket',
    },
    {
        id: 'jean-1',
        name: 'Dress Jeans',
        src: '/templates/jeans1.png',
        category: 'pants',
        garmentLabel: 'Jeans',
        generationCategoryId: 'jeans',
    },
    {
        id: 'jean-2',
        name: 'Basic Jeans',
        src: '/templates/jeans2.png',
        category: 'pants',
        garmentLabel: 'Jeans',
        generationCategoryId: 'jeans',
    },
    {
        id: 'short-1',
        name: 'Basic Shorts',
        src: '/templates/short1.png',
        category: 'shorts',
        garmentLabel: 'Shorts',
        generationCategoryId: 'shorts',
    },
    {
        id: 'short-2',
        name: 'Denim Shorts',
        src: '/templates/short2.png',
        category: 'shorts',
        garmentLabel: 'Denim Shorts',
        generationCategoryId: 'shorts',
    },
    {
        id: 'skirt-1',
        name: 'Basic Skirt',
        src: '/templates/skirt1.png',
        category: 'skirt',
        garmentLabel: 'Skirt',
        generationCategoryId: 'skirt',
    },
    {
        id: 'skirt-2',
        name: 'Box Skirt',
        src: '/templates/skirt2.png',
        category: 'skirt',
        garmentLabel: 'Box Skirt',
        generationCategoryId: 'skirt',
    },
    {
        id: 'skirt-3',
        name: 'Pleated Skirt',
        src: '/templates/skirt3.png',
        category: 'skirt',
        garmentLabel: 'Pleated Skirt',
        generationCategoryId: 'skirt',
    },
    {
        id: 'tank-top-1',
        name: 'Tank Top 1',
        src: '/templates/tank-top1.png',
        category: 'tank-tops',
        garmentLabel: 'Tank Top',
        generationCategoryId: 'tank-top',
    },
    {
        id: 'tank-top-2',
        name: 'Tank Top 2',
        src: '/templates/tank-top2.png',
        category: 'tank-tops',
        garmentLabel: 'Tank Top',
        generationCategoryId: 'tank-top',
    },
    {
        id: 'tank-top-3',
        name: 'Tank Top 3',
        src: '/templates/tank-top3.png',
        category: 'tank-tops',
        garmentLabel: 'Tank Top',
        generationCategoryId: 'tank-top',
    },
];

export function findTemplateBySrcOrName(src: string, name: string): TemplateItem | undefined {
    return TEMPLATES.find((template) => template.src === src || template.name === name);
}
